name: Helm Publish

on:
  push:
    branches: [ eche ]

jobs:
  publish-helmcharts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Helm charts to the gh-pages
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
